[package]
name = "dumbdb-bin"
description = "Binnary for DumbDB"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "main.rs"
